- name: prompt variable declaration
  hosts: host
  vars_prompt:
  - name: username
    prompt: please enter ur username
    private: no
  - name: password
    prompt: please enter password
    private: yes
  tasks:
  - name: calling prompt variables
    ansible.builtin.debug:
     msg: "user name is {{username}} password is {{password}}"